import * as uiComponents from "../sdk/src/components/common";
import * as mediaComponents from "../sdk/src/components/media";

export const getSandboxComponents = () => ({
  VStack: () => new uiComponents.VStackBuilder(),
  HStack: () => new uiComponents.HStackBuilder(),
  Grid: () => new uiComponents.GridBuilder(),
  Card: () => new uiComponents.CardBuilder(),
  Heading: (t: string) => new uiComponents.HeadingBuilder(t),
  Text: (t: string) => new uiComponents.TextBuilder(t),
  Markdown: (c: string) => new uiComponents.MarkdownBuilder(c),
  Badge: (t: string) => new uiComponents.BadgeBuilder(t),
  StatusRow: (l: string) => new uiComponents.StatusRowBuilder(l),
  Divider: () => new uiComponents.DividerBuilder(),
  Spacer: () => new uiComponents.SpacerBuilder(),
  Button: (t: string) => new uiComponents.ButtonBuilder(t),
  Input: (n: string) => new uiComponents.InputBuilder(n),
  Toggle: (n: string) => new uiComponents.ToggleBuilder(n),
  Select: (n: string) => new uiComponents.SelectBuilder(n),
  CodeEditor: (n: string) => new uiComponents.CodeEditorBuilder(n),
  StreamSkeletonList: () => new mediaComponents.StreamSkeletonListBuilder(),
  StreamRow: () => new mediaComponents.StreamRowBuilder(),
  StreamList: () => new mediaComponents.StreamListBuilder(),
  MediaCard: () => new mediaComponents.MediaCardBuilder(),
  HeroSpotlight: () => new mediaComponents.HeroSpotlightBuilder(),
  LoadingSpinner: () => new mediaComponents.LoadingSpinnerBuilder(),
  EpisodesSection: () => new mediaComponents.EpisodesSectionBuilder(),
  MediaCast: () => new mediaComponents.MediaCastBuilder(),
  MediaOverview: () => new mediaComponents.MediaOverviewBuilder(),
  MediaRow: () => new mediaComponents.MediaRowBuilder(),
  MediaPlayer: () => new mediaComponents.MediaPlayerBuilder(),
  ProfileSelector: () => new mediaComponents.ProfileSelectorBuilder(),
  SearchBar: () => new mediaComponents.SearchBarBuilder(),
  StreamFilterBar: () => new mediaComponents.StreamFilterBarBuilder(),
  EpisodeSelector: () => new mediaComponents.EpisodeSelectorBuilder(),
  EpisodeCard: () => new mediaComponents.EpisodeCardBuilder(),
});
